#!/bin/bash
jawaban="Y"
read -p "Apakah kamu yakin akan melakukan setup Aplikasi Web ? (Y/n) " pilih;
if [ $pilih == $jawaban ];
then
echo "=============================>"
echo "Downloading Data"
echo "=============================>"
cd
wget https://github.com/sdcilsy/landing-page/archive/refs/heads/master.zip
echo "=============================>"
echo "Ekstrak File"
echo "=============================>"
unzip master.zip
echo "=============================>"
echo "Memindahkan data"
echo "=============================>"
sudo rm /var/www/html/*
sudo rm -R /var/www/html/*
sudo mv landing-page-master/* home/richard/sp-1
echo "Setup selesai"
exit 0
else
echo "Setup dibatalkan"
fi
